1.1: Khai báo và đọc dữ liệu

In [1]:
# In thông tin sinh viên
print("Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027")
print("-" * 30)

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Đọc tập dữ liệu Bank Marketing
df = pd.read_csv('bank-full.csv', sep=';')

# Xem nhanh 5 dòng đầu tiên
display(df.head())

Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027
------------------------------

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

1.2 Khảo sát sơ bộ dữ liệu

In [2]:
# In thông tin sinh viên
print("Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027")
print("-" * 30)
# Kiểm tra tổng quan thông tin cấu trúc dữ liệu
print("--- Thông tin cấu trúc dữ liệu ---")
df.info()

# Kiểm tra số lượng giá trị thiếu (missing values) trên từng cột
print("\n--- Số lượng giá trị thiếu (Null) ---")
print(df.isnull().sum())

Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027
------------------------------
--- Thông tin cấu trúc dữ liệu ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

--- Số lượng giá trị thiếu (Null) ---
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

1.3 Thống kê mô tả các thuộc tính

In [4]:
print("Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027")
print("-" * 30)
print("-" * 30)
# Thống kê mô tả cho các biến định lượng (như Duration, Cons.price.idx)
display(df.describe())

# Thống kê mô tả cho các biến phân loại (như Job, Marital, Education, Subscribe...)
display(df.describe(include=['O']))

Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027
------------------------------
------------------------------

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

,job,marital,education,default,housing,loan,contact,month,poutcome,y
count,45211,45211,45211,45211,45211,45211,45211,45211,45211,45211
unique,12,3,4,2,2,2,3,12,4,2
top,blue-collar,married,secondary,no,yes,no,cellular,may,unknown,no
freq,9732,27214,23202,44396,25130,37967,29285,13766,36959,39922

1.4 Tiền xử lí dữ liệu

In [5]:
print("Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027")
print("-" * 30)
# Thống kê mô tả cho các biến định lượng (như Duration, Cons.price.idx)
display(df.describe())

# Thống kê mô tả cho các biến phân loại (như Job, Marital, Education, Subscribe...)
display(df.describe(include=['O']))
# 1. Đối với các cột định lượng (ví dụ: Cons.price.idx), điền giá trị thiếu bằng số trung bình (mean)
if 'Cons.price.idx' in df.columns:
    df['Cons.price.idx'] = df['Cons.price.idx'].fillna(df['Cons.price.idx'].mean())

# 2. Đối với các cột phân loại (ví dụ: Job, Marital...), điền giá trị thiếu bằng giá trị xuất hiện nhiều nhất (mode)
for col in ['Job', 'Marital', 'Education', 'Default', 'Loan', 'Subscribe']:
    if col in df.columns and df[col].isnull().sum() > 0:
        most_common = df[col].mode()[0]
        df[col] = df[col].fillna(most_common)

# Kiểm tra lại sau khi xử lý thiếu
print("Số lượng giá trị thiếu sau khi điền:")
print(df.isnull().sum())

Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027
------------------------------

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

,job,marital,education,default,housing,loan,contact,month,poutcome,y
count,45211,45211,45211,45211,45211,45211,45211,45211,45211,45211
unique,12,3,4,2,2,2,3,12,4,2
top,blue-collar,married,secondary,no,yes,no,cellular,may,unknown,no
freq,9732,27214,23202,44396,25130,37967,29285,13766,36959,39922

Số lượng giá trị thiếu sau khi điền:
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

1.5 mã hóa dữ liệu

In [6]:
print("Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027")
print("-" * 30)
# Thống kê mô tả cho các biến định lượng (như Duration, Cons.price.idx)
display(df.describe())

# Thống kê mô tả cho các biến phân loại (như Job, Marital, Education, Subscribe...)
display(df.describe(include=['O']))
# Ví dụ chuyển đổi cột 'y' (hoặc 'Subscribe' tùy theo tên cột thực tế trong file bank.csv) sang 1/0
# Lưu ý: Trong tập bank.csv gốc, cột nhãn thường tên là 'y' thay vì 'Subscribe'
target_col = 'y' if 'y' in df.columns else 'Subscribe'

if target_col in df.columns:
    df['Subscribe_encoded'] = df[target_col].map({'yes': 1, 'no': 0})
    print(df[[target_col, 'Subscribe_encoded']].head())
    print("\n--- Số lượng giá trị thiếu (Null) của các cột ---")
    print(df.isnull().sum())
else:
    print(f"Không tìm thấy cột mục tiêu trong DataFrame. Các cột hiện có là: {df.columns.tolist()}")

Họ và tên:Nguyễn Gia Huy - MSSV: 6451071027
------------------------------

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

,job,marital,education,default,housing,loan,contact,month,poutcome,y
count,45211,45211,45211,45211,45211,45211,45211,45211,45211,45211
unique,12,3,4,2,2,2,3,12,4,2
top,blue-collar,married,secondary,no,yes,no,cellular,may,unknown,no
freq,9732,27214,23202,44396,25130,37967,29285,13766,36959,39922

    y  Subscribe_encoded
0  no                  0
1  no                  0
2  no                  0
3  no                  0
4  no                  0

--- Số lượng giá trị thiếu (Null) của các cột ---
age                  0
job                  0
marital              0
education            0
default              0
balance              0
housing              0
loan                 0
contact              0
day                  0
month                0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
y                    0
Subscribe_encoded    0
dtype: int64